# SPDX-FileCopyrightText: 2026 Freki Geri
# SPDX-License-Identifier: MIT OR Apache-2.0

[package]
name = "vanargand-net"
description = "Pile reseau (rust-libp2p) : transports QUIC/TCP/WebRTC/mDNS/BLE, gossipsub (blocks/txs/msgs/svc), DHT Kademlia."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
vanargand-types.workspace = true
