[package]
name = "vanargand"
version = "0.0.0"
edition = "2021"
authors = ["Freki Geri <geri.freki99@gmail.com>"]
license = "MIT OR Apache-2.0"
description = "Nom nu du projet -- caisse facade/reexport, ou simple redirection vers les vraies caisses. Reserve -- implementation a venir."
repository = "https://github.com/gerifreki99/vanargand"
