// SPDX-FileCopyrightText: 2026 Freki Geri
// SPDX-License-Identifier: MIT OR Apache-2.0

//! Runs the conformance vectors in `spec/vectors/` against this implementation.
//!
//! The vectors are generated by `tools/vectorgen/generate.py`, a second
//! implementation written from the prose in `spec/draft/` rather than from this
//! code. That is what makes these tests worth anything: vectors generated by
//! the implementation they test prove only that the implementation is
//! self-consistent.
//!
//! When one of these fails, **the finding is the disagreement**, not "a test
//! broke". One of the two implementations is wrong, or the specification is
//! ambiguous enough that two readers of it diverged — and the third case is the
//! most valuable of the three.

// This is test code: a panic is the assertion, and a malformed vector file
// should stop the run loudly rather than be handled. The workspace's
// deny-level panic lints exist for library code, and clippy's automatic
// test-code exemption does not reliably reach helpers called *from* a test
// function, so the exemption is stated here rather than left to chance.
#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

use std::collections::BTreeSet;
use std::path::PathBuf;

use serde_json::Value;
use vanargand_types::address::{Address, Network};
use vanargand_types::codec::{Decoder, Encoder};
use vanargand_types::id::AccountId;
use vanargand_types::merkle::list_root;
use vanargand_types::{AlgorithmId, Hash};

fn vectors(name: &str) -> Value {
    let mut path = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    path.pop();
    path.push("spec");
    path.push("vectors");
    path.push(name);
    let text = std::fs::read_to_string(&path)
        .unwrap_or_else(|error| panic!("cannot read {}: {error}", path.display()));
    serde_json::from_str(&text)
        .unwrap_or_else(|error| panic!("cannot parse {}: {error}", path.display()))
}

fn array<'a>(value: &'a Value, key: &str) -> &'a Vec<Value> {
    value
        .get(key)
        .and_then(Value::as_array)
        .unwrap_or_else(|| panic!("vector file has no array '{key}'"))
}

fn text<'a>(value: &'a Value, key: &str) -> &'a str {
    value
        .get(key)
        .and_then(Value::as_str)
        .unwrap_or_else(|| panic!("case has no string '{key}': {value}"))
}

fn hex(value: &str) -> Vec<u8> {
    vanargand_crypto::hash::decode_hex(value).expect("vector contains invalid hex")
}

fn hash(value: &str) -> Hash {
    Hash::from_hex(value).expect("vector contains an invalid digest")
}

// --------------------------------------------------------------------------
// 01 — canonical encoding
// --------------------------------------------------------------------------

#[test]
fn canonical_encoding_vectors_encode() {
    let file = vectors("01-canonical-encoding.json");
    let mut checked = 0_usize;

    for case in array(&file, "encode") {
        let schema = text(case, "schema");
        let expected = hex(text(case, "encoding"));

        let produced = match schema {
            "varint" => {
                let value: u64 = text(case, "value").parse().expect("value is not a u64");
                let mut encoder = Encoder::new();
                encoder.write_varint(value);
                encoder.finish()
            }
            "bytes" => {
                let mut encoder = Encoder::new();
                encoder.write_bytes(&hex(text(case, "value")));
                encoder.finish()
            }
            "string" => {
                let mut encoder = Encoder::new();
                encoder.write_str(text(case, "value"));
                encoder.finish()
            }
            "bool" => {
                let mut encoder = Encoder::new();
                encoder.write_bool(text(case, "value") == "true");
                encoder.finish()
            }
            "option<varint>" => {
                let mut encoder = Encoder::new();
                match text(case, "value") {
                    "none" => {
                        encoder.write_option::<u64>(None);
                    }
                    "some(0)" => {
                        encoder.write_option(Some(&0_u64));
                    }
                    other => panic!("unhandled option vector: {other}"),
                }
                encoder.finish()
            }
            "seq<varint>" => {
                let mut encoder = Encoder::new();
                match text(case, "value") {
                    "[1, 2, 300]" => {
                        encoder.write_seq(&[1_u64, 2, 300]);
                    }
                    other => panic!("unhandled sequence vector: {other}"),
                }
                encoder.finish()
            }
            other => panic!("unknown schema in vectors: {other}"),
        };

        assert_eq!(
            produced,
            expected,
            "encoding disagreed for {schema} = {}",
            text(case, "value")
        );

        // Every encoding must also decode back, and consume its input exactly.
        if schema == "varint" {
            let mut decoder = Decoder::new(&expected).expect("vector is not oversized");
            let value: u64 = text(case, "value").parse().expect("value is not a u64");
            assert_eq!(decoder.read_varint(), Ok(value));
            assert_eq!(decoder.finish(), Ok(()));
        }
        checked += 1;
    }

    assert!(checked > 10, "the vector file looks empty: only {checked} cases");
}

#[test]
fn canonical_encoding_rejection_vectors_are_rejected() {
    let file = vectors("01-canonical-encoding.json");
    let mut checked = 0_usize;

    for case in array(&file, "reject") {
        let schema = text(case, "schema");
        let bytes = hex(text(case, "encoding"));
        let reason = text(case, "reason");

        let accepted = match schema {
            "varint" => {
                let mut decoder = Decoder::new(&bytes).expect("vector is not oversized");
                decoder.read_varint().is_ok() && decoder.finish().is_ok()
            }
            "bool" => {
                let mut decoder = Decoder::new(&bytes).expect("vector is not oversized");
                decoder.read_bool().is_ok() && decoder.finish().is_ok()
            }
            "option<varint>" => {
                let mut decoder = Decoder::new(&bytes).expect("vector is not oversized");
                decoder.read_option::<u64>().is_ok() && decoder.finish().is_ok()
            }
            "bytes" => {
                let mut decoder = Decoder::new(&bytes).expect("vector is not oversized");
                decoder.read_bytes().is_ok() && decoder.finish().is_ok()
            }
            "string" => {
                let mut decoder = Decoder::new(&bytes).expect("vector is not oversized");
                decoder.read_str().is_ok() && decoder.finish().is_ok()
            }
            "set<varint>" => {
                let mut decoder = Decoder::new(&bytes).expect("vector is not oversized");
                decoder.read_set::<u64>().is_ok() && decoder.finish().is_ok()
            }
            other => panic!("unknown schema in rejection vectors: {other}"),
        };

        assert!(
            !accepted,
            "accepted a {schema} encoding that must be rejected ({reason}): {}",
            text(case, "encoding")
        );
        checked += 1;
    }

    assert!(checked > 10, "the rejection set looks empty: only {checked} cases");
}

// --------------------------------------------------------------------------
// 02 — hashing
// --------------------------------------------------------------------------

#[test]
fn every_domain_context_matches_its_vector() {
    let file = vectors("02-hashing.json");
    let mut names = BTreeSet::new();

    for case in array(&file, "registry") {
        let context = text(case, "context");
        let input = hex(text(case, "input"));
        let expected = hash(text(case, "digest"));

        let found = vanargand_crypto::hash::domain::ALL
            .iter()
            .find(|candidate| candidate.as_str() == context)
            .copied()
            .unwrap_or_else(|| panic!("the vectors name a context this build does not have: {context}"));

        assert_eq!(
            vanargand_crypto::hash::hash(found, &input),
            expected,
            "digest disagreed for context {context}"
        );
        names.insert(context.to_owned());
    }

    // The registry in the vectors and the registry in the code must be the
    // same set. A context present in one and not the other is a hash whose
    // separation nobody checked.
    let in_code: BTreeSet<String> = vanargand_crypto::hash::domain::ALL
        .iter()
        .map(|context| context.as_str().to_owned())
        .collect();
    assert_eq!(names, in_code, "the domain registries have drifted apart");
}

#[test]
fn hash_chain_vectors_match() {
    use vanargand_crypto::chain::{ChainCursor, HashChain};

    let file = vectors("02-hashing.json");
    for case in array(&file, "chains") {
        let context_name = text(case, "context");
        let context = vanargand_crypto::hash::domain::ALL
            .iter()
            .find(|candidate| candidate.as_str() == context_name)
            .copied()
            .unwrap_or_else(|| panic!("unknown context {context_name}"));
        let seed = hash(text(case, "seed"));
        let length = case
            .get("length")
            .and_then(Value::as_u64)
            .and_then(|value| u32::try_from(value).ok())
            .expect("length");
        let expected_root = hash(text(case, "root"));

        let chain = HashChain::generate(context, &seed, length).expect("chain generation");
        assert_eq!(chain.root(), expected_root, "root disagreed for {context_name}/{length}");

        let reveals = array(case, "reveals");
        assert_eq!(
            reveals.len(),
            usize::try_from(length).expect("length fits"),
            "reveal count disagreed"
        );

        // Every reveal must both match the vector and verify in sequence.
        let mut cursor = ChainCursor::new(context, expected_root, 4);
        for (offset, reveal) in reveals.iter().enumerate() {
            let index = u32::try_from(offset).expect("index fits") + 1;
            let expected = hash(reveal.as_str().expect("reveal is a string"));
            assert_eq!(chain.reveal(index), Some(expected), "reveal {index} disagreed");
            assert_eq!(cursor.advance(&expected), Ok(1), "reveal {index} did not verify");
        }
    }
}

#[test]
fn merkle_list_vectors_match() {
    let file = vectors("02-hashing.json");
    for case in array(&file, "merkle_list") {
        let leaves: Vec<Hash> = array(case, "leaves")
            .iter()
            .map(|leaf| hash(leaf.as_str().expect("leaf is a string")))
            .collect();
        let expected = hash(text(case, "root"));
        assert_eq!(
            list_root(&leaves),
            expected,
            "Merkle root disagreed for {} leaves",
            leaves.len()
        );
    }
}

// --------------------------------------------------------------------------
// 03 — addresses
// --------------------------------------------------------------------------

#[test]
fn derivation_vectors_match() {
    use vanargand_crypto::derive::{derive_seed, DerivationPath, MasterSeed};

    let file = vectors("03-addresses.json");
    for case in array(&file, "derivations") {
        let components: Vec<u32> = case
            .get("path")
            .and_then(Value::as_array)
            .expect("path")
            .iter()
            .map(|value| {
                u32::try_from(value.as_u64().expect("component is a number"))
                    .expect("component fits in u32")
            })
            .collect();
        let path = DerivationPath::new(components).expect("path is short enough");

        assert_eq!(
            path.encode(),
            hex(text(case, "path_encoding")),
            "path encoding disagreed for {}",
            text(case, "name")
        );

        let master = MasterSeed::from_slice(&hex(text(case, "master_seed")))
            .expect("master seed is 32 bytes");
        assert_eq!(
            derive_seed(&master, &path),
            hash(text(case, "derived_seed")),
            "derived seed disagreed for {}",
            text(case, "name")
        );
    }
}

#[test]
fn identifier_and_address_vectors_match() {
    use vanargand_crypto::sign::VerifyingKey;

    let file = vectors("03-addresses.json");
    for case in array(&file, "identifiers") {
        let algorithm_byte = u8::try_from(
            case.get("algorithm").and_then(Value::as_u64).expect("algorithm"),
        )
        .expect("algorithm byte");
        let algorithm = AlgorithmId::from_byte(algorithm_byte).expect("known algorithm");
        let public_key = hex(text(case, "public_key"));

        let key = VerifyingKey::new(algorithm, public_key).expect("key of the right length");
        let account = AccountId::of_root_key(&key);

        assert_eq!(
            account.to_hex(),
            text(case, "account_id"),
            "account id disagreed for {}",
            text(case, "algorithm_name")
        );
        assert_eq!(
            vanargand_types::id::DeviceId::of_device_key(&key).to_hex(),
            text(case, "device_id"),
            "device id disagreed for {}",
            text(case, "algorithm_name")
        );
        assert_eq!(
            Address::new(Network::Mainnet, account).to_string(),
            text(case, "address_mainnet")
        );
        assert_eq!(
            Address::new(Network::Testnet, account).to_string(),
            text(case, "address_testnet")
        );
    }

    for case in array(&file, "addresses") {
        let payload = hash(text(case, "payload"));
        let account = AccountId::from_hash(payload);
        let mainnet = text(case, "mainnet");
        let testnet = text(case, "testnet");

        assert_eq!(Address::new(Network::Mainnet, account).to_string(), mainnet);
        assert_eq!(Address::new(Network::Testnet, account).to_string(), testnet);
        assert_eq!(
            mainnet.parse::<Address>().expect("vector address parses").account(),
            account
        );
        assert_eq!(
            testnet.parse::<Address>().expect("vector address parses").network(),
            Network::Testnet
        );
    }
}

#[test]
fn bech32_strings_are_recognised_rather_than_dismissed_as_typos() {
    // These are valid Bech32 (BIP-173) and therefore invalid Bech32m. The
    // distinction is worth a test of its own because the two failures send a
    // user looking in completely different places: "this is the wrong kind of
    // address" and "check for a typo" are not the same message.
    //
    // The vectors are machine-checked at generation time — `self_check` in the
    // generator asserts each really does verify under the Bech32 constant —
    // after three hand-transcribed vectors in this project turned out to be
    // wrong.
    let file = vectors("03-addresses.json");
    let cases = array(&file, "bech32_not_bech32m");
    assert!(!cases.is_empty(), "the vector file lost its Bech32 set");

    for case in cases {
        let candidate = case.as_str().expect("a Bech32 vector is a string");
        assert_eq!(
            vanargand_types::bech32::decode(candidate).err(),
            Some(vanargand_types::bech32::Bech32Error::WrongVariantBech32),
            "{candidate} was not recognised as a Bech32 string"
        );
        assert!(Address::parse_on(Network::Mainnet, candidate).is_err());
    }
}

#[test]
fn address_rejection_vectors_are_rejected() {
    let file = vectors("03-addresses.json");
    for case in array(&file, "reject") {
        let candidate = text(case, "address");
        let reason = text(case, "reason");
        assert!(
            Address::parse_on(Network::Mainnet, candidate).is_err(),
            "accepted an address that must be rejected ({reason}): {candidate}"
        );
    }
}
