#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Freki Geri
# SPDX-License-Identifier: MIT OR Apache-2.0
"""Generate the conformance test vectors in ``spec/vectors/``.

This is a **second, independent implementation** of the frozen parts of the
specification, written from the prose in ``spec/draft/`` and deliberately not
from the Rust source. That is the whole point of it: vectors generated by the
implementation they are meant to test prove nothing at all, whereas two
implementations written from the same document and agreeing is evidence that
the document says what its author thought it said.

Where the two disagree, the disagreement is the finding. Neither side wins
automatically — the bug is as likely to be in the prose as in either program.

Written in the plainest Python available, with no dependency but ``blake3``, so
that a reader can check it against the specification by eye.

Usage::

    pip install blake3
    python tools/vectorgen/generate.py            # write the vectors
    python tools/vectorgen/generate.py --check    # verify they are up to date
"""

from __future__ import annotations

import argparse
import json
import pathlib
import sys

from blake3 import blake3

REPO = pathlib.Path(__file__).resolve().parents[2]
VECTORS = REPO / "spec" / "vectors"


# --------------------------------------------------------------------------
# 01 — canonical encoding
# --------------------------------------------------------------------------

MAX_VARINT_BYTES = 10


def varint_encode(value: int) -> bytes:
    """Unsigned LEB128, shortest form."""
    if value < 0 or value > 0xFFFFFFFFFFFFFFFF:
        raise ValueError("varint is u64")
    out = bytearray()
    while value >= 0x80:
        out.append((value & 0x7F) | 0x80)
        value >>= 7
    out.append(value & 0x7F)
    return bytes(out)


def varint_decode(data: bytes) -> tuple[int, int]:
    """Return ``(value, bytes_consumed)``, raising on any non-canonical input."""
    value = 0
    shift = 0
    for index, byte in enumerate(data):
        if index >= MAX_VARINT_BYTES:
            raise ValueError("varint wider than ten bytes")
        payload = byte & 0x7F
        if payload << shift > 0xFFFFFFFFFFFFFFFF:
            raise ValueError("varint overflows u64")
        value |= payload << shift
        if byte & 0x80 == 0:
            if index > 0 and byte == 0:
                raise ValueError("varint is not in shortest form")
            return value, index + 1
        shift += 7
    raise ValueError("varint truncated")


def encode_bytes(data: bytes) -> bytes:
    return varint_encode(len(data)) + data


def encode_seq(items: list[bytes]) -> bytes:
    return varint_encode(len(items)) + b"".join(items)


# --------------------------------------------------------------------------
# 02 — hashing
# --------------------------------------------------------------------------

DOMAINS = [
    "vanargand v1 account id",
    "vanargand v1 device id",
    "vanargand v1 key derivation",
    "vanargand v1 txid",
    "vanargand v1 tx signing",
    "vanargand v1 name commitment",
    "vanargand v1 asset id",
    "vanargand v1 block id",
    "vanargand v1 block signing",
    "vanargand v1 smt leaf",
    "vanargand v1 smt node",
    "vanargand v1 state value",
    "vanargand v1 commitment chain",
    "vanargand v1 payword",
    "vanargand v1 epoch seed",
]


def h(context: str, *parts: bytes) -> bytes:
    """BLAKE3 in key-derivation mode: the only way this protocol hashes."""
    hasher = blake3(derive_key_context=context)
    for part in parts:
        hasher.update(part)
    return hasher.digest(length=32)


def chain_root(context: str, seed: bytes, length: int) -> list[bytes]:
    """Links from root (index 0) to seed (index ``length``)."""
    links = [b""] * (length + 1)
    links[length] = seed
    for index in range(length - 1, -1, -1):
        links[index] = h(context, links[index + 1])
    return links


def merkle_list_root(leaves: list[bytes]) -> bytes:
    """Binary Merkle root over a list, promoting an odd last node unchanged.

    The last node is promoted, never duplicated. Duplicating it is
    CVE-2012-2459: two different lists then produce the same root.
    """
    if not leaves:
        return bytes(32)
    level = [h("vanargand v1 smt leaf", leaf) for leaf in leaves]
    while len(level) > 1:
        nxt = []
        for index in range(0, len(level) - 1, 2):
            nxt.append(h("vanargand v1 smt node", level[index], level[index + 1]))
        if len(level) % 2 == 1:
            nxt.append(level[-1])
        level = nxt
    return level[0]


# --------------------------------------------------------------------------
# 03 — addresses
# --------------------------------------------------------------------------

CHARSET = "qpzry9x8gf2tvdw0s3jn54khce6mua7l"
BECH32M_CONST = 0x2BC830A3


def bech32_polymod(values: list[int]) -> int:
    generator = [0x3B6A57B2, 0x26508E6D, 0x1EA119FA, 0x3D4233DD, 0x2A1462B3]
    checksum = 1
    for value in values:
        top = checksum >> 25
        checksum = ((checksum & 0x1FFFFFF) << 5) ^ value
        for index in range(5):
            checksum ^= generator[index] if ((top >> index) & 1) else 0
    return checksum


def bech32_hrp_expand(hrp: str) -> list[int]:
    return [ord(c) >> 5 for c in hrp] + [0] + [ord(c) & 31 for c in hrp]


def bech32m_encode(hrp: str, data: list[int]) -> str:
    values = bech32_hrp_expand(hrp) + data
    polymod = bech32_polymod(values + [0, 0, 0, 0, 0, 0]) ^ BECH32M_CONST
    checksum = [(polymod >> 5 * (5 - i)) & 31 for i in range(6)]
    return hrp + "1" + "".join(CHARSET[d] for d in data + checksum)


def bech32m_decode(text: str) -> tuple[str, list[int]]:
    if len(text) > 90:
        raise ValueError("too long")
    if text.lower() != text and text.upper() != text:
        raise ValueError("mixed case")
    text = text.lower()
    position = text.rfind("1")
    if position < 1 or position + 7 > len(text):
        raise ValueError("bad separator position")
    hrp, data_part = text[:position], text[position + 1 :]
    if any(not (33 <= ord(c) <= 126) for c in hrp):
        raise ValueError("bad hrp character")
    if any(c not in CHARSET for c in data_part):
        raise ValueError("bad data character")
    data = [CHARSET.index(c) for c in data_part]
    if bech32_polymod(bech32_hrp_expand(hrp) + data) != BECH32M_CONST:
        raise ValueError("bad checksum")
    return hrp, data[:-6]


def convert_bits(data: list[int], frm: int, to: int, pad: bool) -> list[int]:
    accumulator = 0
    bits = 0
    out = []
    maximum = (1 << to) - 1
    for value in data:
        if value < 0 or (value >> frm):
            raise ValueError("value out of range")
        accumulator = (accumulator << frm) | value
        bits += frm
        while bits >= to:
            bits -= to
            out.append((accumulator >> bits) & maximum)
    if pad:
        if bits:
            out.append((accumulator << (to - bits)) & maximum)
    elif bits >= frm or ((accumulator << (to - bits)) & maximum):
        raise ValueError("non-canonical padding")
    return out


def address_text(hrp: str, version: int, payload: bytes) -> str:
    return bech32m_encode(hrp, [version] + convert_bits(list(payload), 8, 5, True))


def account_id(algorithm: int, public_key: bytes) -> bytes:
    return h("vanargand v1 account id", bytes([algorithm]), public_key)


def device_id(algorithm: int, public_key: bytes) -> bytes:
    return h("vanargand v1 device id", bytes([algorithm]), public_key)


def encode_path(components: list[int]) -> bytes:
    if len(components) > 8:
        raise ValueError("path too long")
    return bytes([len(components)]) + b"".join(
        c.to_bytes(4, "little") for c in components
    )


def derive_seed(master: bytes, components: list[int]) -> bytes:
    return h("vanargand v1 key derivation", encode_path(components), master)


# --------------------------------------------------------------------------
# Self-check: BIP-350 reference vectors
# --------------------------------------------------------------------------

# The reference vectors from BIP-350. The two long ones are written as
# expressions rather than as literals because transcribing an 83-character run
# of the same letter by hand is how a reference vector silently stops being one
# — which is exactly what happened on the first attempt here, and what this
# self-check caught.
BIP350_VALID = [
    "A1LQFN3A",
    "a1lqfn3a",
    "an83characterlonghumanreadablepartthatcontainsthet"
    "heexcludedcharactersbioandnumber11sg7hg6",
    "abcdef1l7aum6echk45nj3s0wdvt2fg8x9yrzpqzd3ryx",
    "11" + "l" * 83 + "udsr8",
    "split1checkupstagehandshakeupstreamerranterredcaperredlc445v",
    "?1v759aa",
]

BIP350_INVALID = [
    "qyrz8wqd2c9m",
    "1qyrz8wqd2c9m",
    "y1b0jsk6g",
    "lt1igcx5c0",
    "in1muywd",
    "mm1crxm3i",
    "au1s5cgom",
    "M1VUXWEZ",
    "16plkw9",
    "1p2gdwpf",
    "A1G7SGD8",  # valid Bech32, not Bech32m
]


def self_check() -> None:
    for text in BIP350_VALID:
        bech32m_decode(text)
    for text in BIP350_INVALID:
        try:
            bech32m_decode(text)
        except ValueError:
            continue
        raise AssertionError(f"BIP-350 invalid vector was accepted: {text}")

    for value in [0, 1, 127, 128, 300, 2**32 - 1, 2**64 - 1]:
        assert varint_decode(varint_encode(value)) == (value, len(varint_encode(value)))
    for bad in [b"\x81\x00", b"\x80\x00", b"\xff\x80\x00"]:
        try:
            varint_decode(bad)
        except ValueError:
            continue
        raise AssertionError(f"non-canonical varint accepted: {bad!r}")

    assert len(set(DOMAINS)) == len(DOMAINS), "duplicate domain context"


# --------------------------------------------------------------------------
# Vector files
# --------------------------------------------------------------------------


def hx(data: bytes) -> str:
    return data.hex()


def build_canonical_encoding() -> dict:
    encode_cases = []
    for value in [0, 1, 2, 127, 128, 129, 255, 256, 300, 16383, 16384,
                  2**32 - 1, 2**32, 2**63, 2**64 - 1]:
        encode_cases.append(
            {"schema": "varint", "value": str(value), "encoding": hx(varint_encode(value))}
        )

    for raw in [b"", b"\x00", b"hello", bytes(range(256))]:
        encode_cases.append(
            {"schema": "bytes", "value": hx(raw), "encoding": hx(encode_bytes(raw))}
        )

    for text in ["", "a", "héllo", "é"]:
        encode_cases.append(
            {
                "schema": "string",
                "value": text,
                "encoding": hx(encode_bytes(text.encode("utf-8"))),
            }
        )

    encode_cases.append(
        {"schema": "bool", "value": "false", "encoding": "00"},
    )
    encode_cases.append(
        {"schema": "bool", "value": "true", "encoding": "01"},
    )
    encode_cases.append(
        {"schema": "option<varint>", "value": "none", "encoding": "00"},
    )
    encode_cases.append(
        {"schema": "option<varint>", "value": "some(0)", "encoding": "0100"},
    )
    encode_cases.append(
        {
            "schema": "seq<varint>",
            "value": "[1, 2, 300]",
            "encoding": hx(encode_seq([varint_encode(1), varint_encode(2), varint_encode(300)])),
        }
    )

    reject_cases = [
        {"schema": "varint", "encoding": "8100", "reason": "not in shortest form"},
        {"schema": "varint", "encoding": "8000", "reason": "not in shortest form"},
        {"schema": "varint", "encoding": "ff8000", "reason": "not in shortest form"},
        {"schema": "varint", "encoding": "80808080808080808000",
         "reason": "ten bytes ending in zero is still not shortest form"},
        {"schema": "varint", "encoding": "80", "reason": "truncated"},
        {"schema": "varint", "encoding": "ffffffffffffffffff02",
         "reason": "overflows u64"},
        {"schema": "varint", "encoding": "ffffffffffffffffffff01",
         "reason": "wider than ten bytes"},
        {"schema": "bool", "encoding": "02", "reason": "bool must be 00 or 01"},
        {"schema": "bool", "encoding": "ff", "reason": "bool must be 00 or 01"},
        {"schema": "option<varint>", "encoding": "02", "reason": "option tag must be 00 or 01"},
        {"schema": "bytes", "encoding": "05616263", "reason": "declared length exceeds input"},
        {"schema": "string", "encoding": "02fffe", "reason": "not valid UTF-8"},
        {"schema": "varint", "encoding": "0100", "reason": "trailing bytes after the object"},
        {"schema": "set<varint>", "encoding": "03030102",
         "reason": "set elements are not in strictly ascending encoded order"},
        {"schema": "set<varint>", "encoding": "020707",
         "reason": "duplicate set element"},
        {"schema": "set<varint>", "encoding": "02ff018002",
         "reason": "255 encodes as ff01 and 256 as 8002, so this is descending in encoded order"},
    ]

    return {
        "_": "Generated by tools/vectorgen/generate.py — do not edit by hand.",
        "spec": "spec/draft/01-canonical-encoding.md",
        "encode": encode_cases,
        "reject": reject_cases,
    }


def build_hashing() -> dict:
    fixed = b"vanargand conformance input"
    registry = [
        {"context": context, "input": hx(fixed), "digest": hx(h(context, fixed))}
        for context in DOMAINS
    ]

    chains = []
    for context in ["vanargand v1 commitment chain", "vanargand v1 payword"]:
        for length in [0, 1, 2, 5, 16]:
            seed = bytes([length]) * 32
            links = chain_root(context, seed, length)
            chains.append(
                {
                    "context": context,
                    "seed": hx(seed),
                    "length": length,
                    "root": hx(links[0]),
                    "reveals": [hx(link) for link in links[1:]],
                }
            )

    merkle = []
    for count in range(0, 6):
        leaves = [bytes([index]) * 32 for index in range(count)]
        merkle.append(
            {
                "leaves": [hx(leaf) for leaf in leaves],
                "root": hx(merkle_list_root(leaves)),
            }
        )

    return {
        "_": "Generated by tools/vectorgen/generate.py — do not edit by hand.",
        "spec": "spec/draft/02-hashing.md",
        "registry": registry,
        "chains": chains,
        "merkle_list": merkle,
    }


def build_addresses() -> dict:
    master = bytes([0x42]) * 32
    paths = [
        ("root", [0]),
        ("device 0", [1, 0]),
        ("device 1", [1, 1]),
        ("scan", [2]),
        ("one-time 7", [3, 7]),
        ("payword 0", [4, 0]),
        ("commitment 0", [5, 0]),
        ("empty", []),
        ("max component", [0xFFFFFFFF]),
    ]
    derivations = [
        {
            "name": name,
            "path": components,
            "path_encoding": hx(encode_path(components)),
            "master_seed": hx(master),
            "derived_seed": hx(derive_seed(master, components)),
        }
        for name, components in paths
    ]

    # Identifiers are computed from *given* public key bytes rather than from a
    # seed, so that they can be checked without an ML-DSA implementation.
    identifiers = []
    for algorithm, length, label in [(0x01, 1312, "ML-DSA-44"), (0x10, 32, "INSECURE-TEST")]:
        for filler in [0x00, 0xFF, 0xA5]:
            public_key = bytes([filler]) * length
            account = account_id(algorithm, public_key)
            identifiers.append(
                {
                    "algorithm": algorithm,
                    "algorithm_name": label,
                    "public_key": hx(public_key),
                    "account_id": hx(account),
                    "device_id": hx(device_id(algorithm, public_key)),
                    "address_mainnet": address_text("van", 0, account),
                    "address_testnet": address_text("tvan", 0, account),
                }
            )

    addresses = [
        {
            "payload": hx(payload),
            "version": 0,
            "mainnet": address_text("van", 0, payload),
            "testnet": address_text("tvan", 0, payload),
        }
        for payload in [bytes(32), bytes([0xFF]) * 32, bytes(range(32))]
    ]

    rejects = [
        {"address": "van1qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq",
         "reason": "bad checksum"},
        {"address": "Van1" + address_text("van", 0, bytes(32))[4:],
         "reason": "mixed case"},
        {"address": address_text("van", 0, bytes(32))[:-1],
         "reason": "truncated, checksum fails"},
        {"address": address_text("tvan", 0, bytes(32)),
         "reason": "test network address, rejected on mainnet"},
        {"address": "A1G7SGD8", "reason": "Bech32 rather than Bech32m"},
        {"address": "van1qqqqq", "reason": "payload is not 32 bytes"},
    ]

    return {
        "_": "Generated by tools/vectorgen/generate.py — do not edit by hand.",
        "spec": "spec/draft/03-addresses.md",
        "derivations": derivations,
        "identifiers": identifiers,
        "addresses": addresses,
        "reject": rejects,
    }


BUILDERS = {
    "01-canonical-encoding.json": build_canonical_encoding,
    "02-hashing.json": build_hashing,
    "03-addresses.json": build_addresses,
}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify the committed vectors match what this script generates",
    )
    args = parser.parse_args()

    self_check()

    VECTORS.mkdir(parents=True, exist_ok=True)
    stale = []
    for name, builder in BUILDERS.items():
        path = VECTORS / name
        text = json.dumps(builder(), indent=2, ensure_ascii=False) + "\n"
        if args.check:
            current = path.read_text(encoding="utf-8") if path.exists() else ""
            if current != text:
                stale.append(name)
        else:
            path.write_text(text, encoding="utf-8")
            print(f"wrote {path.relative_to(REPO)}")

    if args.check:
        if stale:
            print("stale vectors: " + ", ".join(stale), file=sys.stderr)
            print("run: python tools/vectorgen/generate.py", file=sys.stderr)
            return 1
        print("vectors are up to date")
    return 0


if __name__ == "__main__":
    sys.exit(main())
